version: "3.9"
services:
  api:
    image: api:latest
    ports:
      - '5001:5001'
    expose:
      - '5001'
    networks:
      -  dbnet

    
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: False
      
    links:
      - api
    networks:
      - dbnet
  redis:
    image: "redis:alpine" 

networks:
  dbnet:
    driver: bridge
